"""update user and room relationships

Revision ID: f4ae205012bd
Revises: e855a67b0663
Create Date: 2025-11-06 18:53:30.308086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ae205012bd'
down_revision: Union[str, Sequence[str], None] = 'e855a67b0663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('rooms_creator_id_fkey'), 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'user'::character varying"),
               existing_nullable=True)
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key(op.f('rooms_creator_id_fkey'), 'rooms', 'users', ['creator_id'], ['id'])
    op.alter_column('rooms', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
